# Generated by Django 5.0.3 on 2024-03-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Homes',
        ),
    ]
