# Generated by Django 5.0.3 on 2024-03-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0006_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='categ',
            field=models.CharField(default=0.09090909090909091, max_length=400),
            preserve_default=False,
        ),
    ]
