# Generated by Django 5.0.3 on 2024-03-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0008_rename_categ_package_ln1_package_ln10_package_ln11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='ln10',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='package',
            name='ln11',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='package',
            name='ln12',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='package',
            name='ln13',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='package',
            name='ln7',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='package',
            name='ln8',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='package',
            name='ln9',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
