# Generated by Django 5.0.3 on 2024-03-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0010_homes_email_homes_message_homes_nam_homes_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homes',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
