# Generated by Django 5.0.3 on 2024-03-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0011_alter_homes_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homes',
            name='phone',
        ),
        migrations.AddField(
            model_name='homes',
            name='number',
            field=models.IntegerField(default=0.09090909090909091),
            preserve_default=False,
        ),
    ]
