# Generated by Django 5.0.3 on 2024-03-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0013_rename_nam_homes_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homes',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
