# Generated by Django 5.0.3 on 2024-03-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0014_alter_homes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homes',
            name='names',
            field=models.CharField(max_length=250),
        ),
    ]
