# Generated by Django 5.0.3 on 2024-03-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0015_alter_homes_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homes',
            name='email',
            field=models.CharField(max_length=250),
        ),
    ]
